export const COURSE_LIST_REQUEST = "COURSE_LIST_REQUEST";
export const COURSE_LIST_SUCCESS = "COURSE_LIST_SUCCESS";
export const COURSE_LIST_FAIL = "COURSE_LIST_FAIL";

export const COURSE_DELETE_REQUEST = "COURSE_DELETE_REQUEST";
export const COURSE_DELETE_SUCCESS = "COURSE_DELETE_SUCCESS";
export const COURSE_DELETE_FAIL = "COURSE_DELETE_FAIL";

export const COURSE_CREATE_REQUEST = "COURSE_CREATE_REQUEST";
export const COURSE_CREATE_SUCCESS = "COURSE_CREATE_SUCCESS";
export const COURSE_CREATE_FAIL = "COURSE_CREATE_FAIL";
export const COURSE_CREATE__REST = "COURSE_CREATE__REST";

export const COURSE_VIEW_REQUEST = "COURSE_VIEW_REQUEST";
export const COURSE_VIEW_SUCCESS = "COURSE_VIEW_SUCCESS";
export const COURSE_VIEW_FAIL = "COURSE_VIEW_FAIL";
export const COURSE_VIEW__REST = "COURSE_VIEW__REST";

export const COURSE_EDIT_REQUEST = "COURSE_EDIT_REQUEST";
export const COURSE_EDIT_SUCCESS = "COURSE_EDIT_SUCCESS";
export const COURSE_EDIT_FAIL = "COURSE_EDIT_FAIL";
export const COURSE_EDIT__REST = "COURSE_EDIT__REST";

export const COURSE_DETAILS_REQUEST = "COURSE_DETAILS_REQUEST";
export const COURSE_DEATAILS_SUCCESS = "COURSE_DEATAILS_SUCCESS";
export const COURSE_DETAILS_FAIL = "COURSE_DETAILS_FAIL";