export const TESTIMONIAL_LIST_REQUEST = "TESTIMONIAL_LIST_REQUEST";
export const TESTIMONIAL_LIST_SUCCESS = "TESTIMONIAL_LIST_SUCCESS";
export const TESTIMONIAL_LIST_FAIL = "TESTIMONIAL_LIST_FAIL";

export const TESTIMONIAL_DELETE_REQUEST = "TESTIMONIAL_DELETE_REQUEST";
export const TESTIMONIAL_DELETE_SUCCESS = "TESTIMONIAL_DELETE_SUCCESS";
export const TESTIMONIAL_DELETE_FAIL = "TESTIMONIAL_DELETE_FAIL";

export const TESTIMONIAL_CREATE_REQUEST = "TESTIMONIAL_CREATE_REQUEST";
export const TESTIMONIAL_CREATE_SUCCESS = "TESTIMONIAL_CREATE_SUCCESS";
export const TESTIMONIAL_CREATE_FAIL = "TESTIMONIAL_CREATE_FAIL";
export const TESTIMONIAL_CREATE__REST = "TESTIMONIAL_CREATE__REST";

export const TESTIMONIAL_VIEW_REQUEST = "TESTIMONIAL_VIEW_REQUEST";
export const TESTIMONIAL_VIEW_SUCCESS = "TESTIMONIAL_VIEW_SUCCESS";
export const TESTIMONIAL_VIEW_FAIL = "TESTIMONIAL_VIEW_FAIL";
export const TESTIMONIAL_VIEW__REST = "TESTIMONIAL_VIEW__REST";

export const TESTIMONIAL_EDIT_REQUEST = "TESTIMONIAL_EDIT_REQUEST";
export const TESTIMONIAL_EDIT_SUCCESS = "TESTIMONIAL_EDIT_SUCCESS";
export const TESTIMONIAL_EDIT_FAIL = "TESTIMONIAL_EDIT_FAIL";
export const TESTIMONIAL_EDIT__REST = "TESTIMONIAL_EDIT__REST";

export const TESTIMONIAL_DETAILS_REQUEST = "TESTIMONIAL_DETAILS_REQUEST";
export const TESTIMONIAL_DEATAILS_SUCCESS = "TESTIMONIAL_DEATAILS_SUCCESS";
export const TESTIMONIAL_DETAILS_FAIL = "TESTIMONIAL_DETAILS_FAIL";