export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const USER_PROFILE_UPDATE_REQUEST = "USER_PROFILE_UPDATE_REQUEST";
export const USER_PROFILE_UPDATE_SUCCESS = "USER_PROFILE_UPDATE_SUCCESS";
export const USER_PROFILE_UPDATE_FAIL = "USER_PROFILE_UPDATE_FAIL";
export const USER_PROFILE_UPDATE_REST = "USER_PROFILE_UPDATE_REST";

export const USER_REST_PASSWORD_REQUEST = "USER_REST_PASSWORD_REQUEST";
export const USER_REST_PASSWORD_SUCCESS = "USER_REST_PASSWORD_SUCCESS";
export const USER_REST_PASSWORD_FAIL = "USER_REST_PASSWORD_FAIL";
export const USER_REST_PASSWORD_REST = "USER_REST_PASSWORD_REST";

export const USER_REG_REQUEST = "USER_REG_REQUEST";
export const USER_REG_SUCCESS = "USER_REG_SUCCESS";
export const USER_REG_FAIL = "USER_REG_FAIL";
export const USER_REG_REST = "USER_REG_REST";
